#!/bin/bash
# Circuit Stability Environment Activation Script
# Generated by install.sh on $(date)

echo "🧠 Activating Circuit Stability Environment..."

# Activate conda environment
if [ -f "/opt/miniconda3/etc/profile.d/conda.sh" ]; then
    source /opt/miniconda3/etc/profile.d/conda.sh
elif [ -f "/root/miniconda3/etc/profile.d/conda.sh" ]; then
    source /root/miniconda3/etc/profile.d/conda.sh
elif [ -f "$HOME/miniconda3/etc/profile.d/conda.sh" ]; then
    source "$HOME/miniconda3/etc/profile.d/conda.sh"
elif [ -f "/usr/local/miniconda3/etc/profile.d/conda.sh" ]; then
    source /usr/local/miniconda3/etc/profile.d/conda.sh
fi

conda activate circuit-stability

# Set Python path
export PYTHONPATH="$PYTHONPATH:/workspace/JAKS/circuit-stability/code/src"

# Verify environment
echo "✓ Environment activated: $(conda info --envs | grep '*' | awk '{print $1}')"
python -c "
import torch
import transformer_lens
print(f'✓ PyTorch {torch.__version__} (CUDA: {torch.cuda.is_available()})')
print('✓ TransformerLens loaded successfully')
try:
    import sys; sys.path.insert(0, '/workspace/JAKS/circuit-stability/code/src')
    from cdatasets import DatasetBuilder
    print(f'✓ Circuit Stability Framework (Datasets: {len(list(DatasetBuilder.ids.keys()))})')
except ImportError as e:
    print(f'⚠ Framework import issue: {e}')
"

echo "🚀 Environment ready for circuit stability research!"